---
- name: (Debian) Create nginx group
  ansible.builtin.group:
    name: "{{ nginx_group }}"
    state: present

- name: (Debian) Create nginx user
  ansible.builtin.user:
    name: "{{ nginx_user }}"
    state: present
    create_home: false
    groups:
      - nobody

- name: (Debian) Silently stop Apache if running
  ansible.builtin.service:
    name: "{{ apache_daemon | default('apache2') }}"
    state: stopped
  changed_when: false
  failed_when: false
