---
# tasks file for inmotion.nginx-proxy

- name: Include variables and set facts
  include: facts.yml

- name: Include os_family tasks
  include: "{{ ansible_os_family }}.yml"
  vars:
    targets:
      - Debian
      - RedHat
  when: ansible_os_family in targets

- name: Install NGINX packages
  package:
    name: "{{ nginx_packages }}"
    state: present

- name: Create NGINX configuration directories
  file:
    name: "{{ item }}"
    state: directory
  with_items: "{{ nginx_config_dirs }}"

- name: Set ownership for NGINX cache directories
  file:
    name: /var/nginx/cache
    owner: nginx
    group: nginx
    state: directory
    recurse: yes

- name: Create pidfile
  file:
    name: "{{ nginx_pid }}"
    state: touch
  changed_when: false

- name: Configure NGINX
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - etc/nginx/nginx.conf
    - etc/nginx/mime.types
    - etc/nginx/proxy.conf

- name: Include systemd restart configuation
  include: systemd.yml
  when: >-
    ( nginx_systemd_restart|default(False)
    or systemd_restart|default(False) )
    and systemd_restart_setting is defined

# SELinux only
- name: Enable and configure SELinux
  include: selinux.yml
  when:
    - selinux_enabled is defined
    - selinux_enabled
    - ansible_os_family == "RedHat"

- name: Start and enable NGINX
  systemd:
    name: "{{ nginx_daemon }}"
    state: started
    daemon_reload: yes
    enabled: true

- name: Silently start and enable Apache
  service:
    name: "{{ apache_daemon | default('httpd') }}"
    state: started
    enabled: true
  changed_when: false
  failed_when: false
